name: 'W&B Artifact to Kaggle Dataset'
description: 'Upload the model saved as W&B Artifact to Kaggle Dataset'
branding:
  icon: 'box'  
  color: 'blue'

inputs:
  artifact_name:
    description: 'Name of the W&B artifact in the format <wandb profile id>/<wandb project name>/<artifact name>'
    required: true
    default: 'ayut/sr_ffhq/3jygvqe3_model'

  root_path:
    description: 'Path where the model will be downloaded'
    required: false
    default: 'model'

  id:
    description: "Dataset identifier in format {username}/{dataset})."
    required: true
    default: "{KAGGLE_USERNAME}/{GITHUB_REPO_NAME}"

  title:
    description: "Title of the dataset, only if it has to be created."
    required: true
    default: "dataset id"

  is_public:
    description: "Create publicly (default is private)."
    required: false
    default: false
    
  kaggle_username:
    description: "Get kaggle username from secrets"
    required: true
    
  kaggle_key:
    description: "Get secret Kaggle key from secrets"
    required: true

runs:
  using: "composite"
  steps:
    - run: echo Artifact Path ${{ inputs.artifact_name }}.
      shell: bash

    - name: Run download_model_artifact.py
      run: python download_model_artifact.py --artifact_name ${{ inputs.artifact_name }} --root_path ${{ inputs.root_path }}
      shell: bash

    - name: Upload as Kaggle Dataset
      uses: jaimevalero/push-kaggle-dataset@v3
      env:
        KAGGLE_USERNAME: ${{ inputs.kaggle_username }}
        KAGGLE_KEY: ${{ inputs.kaggle_key }}
      with:
        id: ${{ inputs.id }}
        title: ${{ inputs.title }}
        files: ./${{ inputs.root_path }}
        is_public: ${{ inputs.is_public }}
