name: 'Download the model saved as W&B Artifact'
description: 'Provide the name of the W&B model artifact where the model is saved. You can find it by visiting the artifact page of your W&B workspace.'
inputs:
  artifact_name:
    description: 'Name of the W&B artifact in the format <wandb profile id>/<wandb project name>/<artifact name>'
    required: true
    default: 'ayut/sr_ffhq/3jygvqe3_model'
  root_path:
    description: 'Path where the model will be downloaded'
    required: false
    default: 'model'
outputs:
  artifact_dir_path:
    description: "Path to the Artifact Directory to be uploaded as Kaggle Dataset."
    value: ./${{ inputs.root_path  }}
runs:
  using: "composite"
  steps:
    - run: echo Artifact Path ${{ inputs.artifact_name }}.
      shell: bash
    - uses: jungwinter/split@v2
      id: split
      with:
        msg: ${{ inputs.artifact_name }}
    - run: echo ${{ steps.split.outputs._2 }}
    - name: Run download_model_artifact.py
      run: python download_model_artifact.py --artifact_name ${{ inputs.artifact_name }} --root_path ${{ inputs.root_path }}
      shell: bash
