name: 'Download the model saved as W&B Artifact'
description: 'Provide the name of the W&B model artifact where the model is saved. You can find it by visiting the artifact page of your W&B workspace.'
inputs:
  artifact_path:
    description: 'Artifact path of the format <wandb profile id>/<wandb project name>/<artifact name>'
    required: true
    default: 'ayut/sr_ffhq/3jygvqe3_model'
outputs:
  artifact_dir_path:
    description: "Path to the Artifact Directory to be uploaded as Kaggle Dataset."
    value: ".artifact/${{ steps.target_path.outputs.artifact_model_name}}"
runs:
  using: "composite"
  steps:
    - run: echo Artifact Path ${{ inputs.artifact_path }}.
      shell: bash
    - name: Run download_model_artifact.py
      run: python download_model_artifact.py --artifact_name ${{ inputs.artifact_path }}
      shell: bash
    - name: Get target dir to be uploaded as Kaggle dataset
      id: target_path
      run: |
        IFS='/' read -r -a array <<< "${{ inputs.artifact_path }}"
        echo "::set-output name=artifact_model_name::$(echo ${{ array[0]} })"
      shell: bash
