name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install the packages
        uses: BSFishy/pip-action@v1
        with:
          packages: wandb kaggle
      - name: Loging W&B 
        shell: bash
        env:
          WANDB_API: ${{ secrets.WANDB_KEY }}
        run: |
          wandb login "$WANDB_API"
      - name: Kaggle Login
        shell: bash
        run: |
          export KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}
          export KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}
      - name: Download the model
        run: python download_model_artifact.py
