name: Upload model saved as W&B artifact as Kaggle Dataset
on: [push]
jobs:
  wandb-kaggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install the packages
        uses: BSFishy/pip-action@v1
        with:
          packages: wandb kaggle

      - name: Loging W&B and Kaggle
        shell: bash
        env:
          WANDB_API: ${{ secrets.WANDB_KEY }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: wandb login "$WANDB_API"

      - name: Download and Upload
        uses: ./.github/actions/download_artifact
        with:
          artifact_name: 'ayut/convnext/16vi9e31_model'
          id: 'ayut/test-dataset'
          title: 'Testing github actions for uploading datasets'
          is_public: true
